x-app:
  &default
  networks:
    - mynetwork

services:
  database:
    <<: *default
    image: mongo
    container_name: project_database
    hostname: database
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=local
      - MONGO_INITDB_ROOT_PASSWORD=lacol
    volumes:
      - ProjectMongoVolume:/data/db
    ports:
      - 5002:27017
    restart: unless-stopped

  simulator:
    <<: *default
    build:
      context: ./simulation
      dockerfile: ./Dockerfile
      args:
        - WEB_SOCKET_PORT=8001
        - SIMULATION_PORT=9854
    hostname: simulation
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: unless-stopped

  client:
    <<: *default
    build:
      context: ./backend/client
      dockerfile: ./Dockerfile
      target: final
    hostname: webui
    depends_on:
      - server
    ports:
      - "5001:5001"
    restart: unless-stopped

  server:
    <<: *default
    build:
      context: ./backend/server
      dockerfile: ./Dockerfile
      target: final
    environment:
      DB_CONNECTION_STRING: "mongodb://local:lacol@database:27017/"
      ARGOS_HOSTNAME: simulation
      IS_SIMULATION: ${IS_SIMULATION}
    hostname: backend
    privileged: true
    volumes:
      - "/dev:/dev"
    depends_on:
      - database
      - simulator
    ports:
      - "5000:5000"
    restart: unless-stopped

networks:
  mynetwork:


volumes:
  ProjectMongoVolume: {}
